name: Aws cli

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
   gh-actions-awscli:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: AWS Assume Role
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: us-east-1
                role-session-name: AssumeRoleSession
                role-to-assume: arn:aws:iam::975049932312:role/githubactions3fullaccess
            - name: AWS CLI   
              run: |
                aws sts get-caller-identity
                aws s3 ls